#!/usr/bin/env python3
"""Generate Unicode 9 tables: main.py UnicodeData.txt CaseFolding.txt > unicode_tables.go.
Inputs: https://www.unicode.org/Public/9.0.0/ucd/{UnicodeData,CaseFolding}.txt
The Unicode data license is in ../../UNICODE-LICENSE.txt.
"""
import sys
print('// Code generated by internal/genunicode/main.py from Unicode 9.0.0; DO NOT EDIT.\npackage apfs')
rows = [s.rstrip('\n').split(';') for s in open(sys.argv[1])]
print('var combiningClass = map[rune]uint8{')
for r in rows:
    if int(r[3]): print(f'0x{r[0]}: {r[3]},')
print('}\nvar decomposition = map[rune]string{')
for r in rows:
    if r[5] and not r[5].startswith('<'):
        value = ''.join('\\U%08x' % int(c,16) for c in r[5].split())
        print(f'0x{r[0]}: "{value}",')
print('}\nvar caseFold = map[rune]string{')
for line in open(sys.argv[2]):
    line = line.split('#')[0].strip()
    if not line: continue
    cp,status,mapping,*_ = [x.strip() for x in line.split(';')]
    if status in ('C', 'F'):
        value = ''.join('\\U%08x' % int(c,16) for c in mapping.split())
        print(f'0x{cp}: "{value}",')
print('}')
